---
# tasks file for sas_solr_start
- name: Start SOLR
  shell: /sas/home/solr-5.5.5/bin/solr start -p 8983 -m 8g

- name: Check if SOLR is running
  shell: /sas/home/solr-5.5.5/bin/solr status

# - name: Start Deployment Agent
#   shell: /sas/home/SASDeploymentAgent/9.4/agentadmin.sh start

# - name: Check if Deplomyent Agent is running
#   shell: /sas/home/SASDeploymentAgent/9.4/agentadmin.sh stat up

# - name: Start SAS Services
#   shell: /sas/config/Lev1/sas.servers start

# - name: Check if SAS Services are running
#   shell: /sas/config/Lev1/sas.servers status